#!/bin/bash
source state;
dbname=$1;
if [[ $1 == '' ]]
then
    echo "no name entered";
    exit;
fi
for dir in `ls -F $dbloc | grep '/'`
do
    if [[ $dir == $dbname/ ]]
    then
        awk '{if($0 !~ "^currdb*"){print $0}}' state > out.temp && mv out.temp state;
        echo "currdb=$dbname" >> state
        exit;
    fi
done
echo "database $dbname not exist";